# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible

title: Timur Ergen
email: te@mpifg.de
description: tergen.org
shortabout: >-
    I'm a researcher at the Center for European 
    Studies at Harvard University and the Max 
    Planck Institute for the Study of Societies.
    My research investigates energy
    transitions, economic competition,
    and the history of the postindustrial
    economy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tergen.org" 
twitter_username: tmrergen
github_username:  tergen
employer: Center for European Studies (CES) Harvard University
street: 27 Kirkland Street
city: Cambridge, MA 02138
country: United States
employerweb: https://ces.fas.harvard.edu
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
show_excerpts: true
theme: minima
excerpt_separator: <!--more-->
assets:
  sources:
    - _assets
    - _assets/stylesheets
    - _assets/fonts
    - _assets/icons

menu:
  main:
      - Name: "About"
        URL: "/about"
      - Name: "Publications"
        URL: "/publications"
      - Name: "Teaching"
        URL: "/teaching"
      - Name: "Events"
        URL: "/events"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
